import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, Flex, Heading, Text, Link } from "@chakra-ui/react";

const Home: NextPage = () => (
  <Box px={2}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Flex
      minHeight="100vh"
      py={4}
      direction="column"
      justify="center"
      align="center"
    >
      <Heading as="h1" m={0} size="4xl" textAlign="center">
        Welcome to{" "}
        <Link href="https://nextjs.org" isExternal>
          Next.js!
        </Link>
      </Heading>

      <Text my={4} mx={0} fontSize="2xl" textAlign="center">
        Get started by editing <code>pages/index.tsx</code>
      </Text>

      <Flex
        align="center"
        justify="center"
        wrap="wrap"
        maxWidth="800px"
        gap={4}
      >
        <Link
          href="https://nextjs.org/docs"
          m={1}
          padding={2}
          border="1px solid #eaeaea"
          borderRadius="10px"
          maxWidth="300px"
          minHeight="160px"
        >
          <Heading as="h2">Documentation &rarr;</Heading>
          <p>Find in-depth information about Next.js features and API.</p>
        </Link>

        <Link
          href="https://nextjs.org/learn"
          m={1}
          padding={2}
          border="1px solid #eaeaea"
          borderRadius="10px"
          maxWidth="300px"
          minHeight="160px"
        >
          <Heading as="h2">Learn &rarr;</Heading>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </Link>

        <Link
          href="https://github.com/vercel/next.js/tree/canary/examples"
          m={1}
          padding={2}
          border="1px solid #eaeaea"
          borderRadius="10px"
          maxWidth="300px"
          minHeight="160px"
        >
          <Heading as="h2">Examples &rarr;</Heading>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </Link>

        <Link
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          m={1}
          padding={2}
          border="1px solid #eaeaea"
          borderRadius="10px"
          maxWidth="300px"
          minHeight="160px"
        >
          <Heading as="h2">Deploy &rarr;</Heading>
          <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
        </Link>
      </Flex>
    </Flex>

    <Flex
      as="footer"
      py={2}
      borderTop="1px solid #eaeaea"
      justify="center"
      align="center"
    >
      <Link
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{" "}
        <span style={{ height: "1rem", marginLeft: "0.5rem" }}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </Link>
    </Flex>
  </Box>
);

export default Home;
