import type { NextPage } from "next";
import Head from "next/head";
import { Box, Flex, Heading, Text, Link } from "@chakra-ui/react";

const Home: NextPage = () => (
  <Box px={8}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Flex
      minHeight="100vh"
      py={16}
      direction="column"
      justify="center"
      align="center"
    >
      <Heading as="h1" m={0} size="4xl" textAlign="center">
        Welcome to{" "}
        <Link href="https://nextjs.org" isExternal>
          Next.js!
        </Link>
      </Heading>

      <Text my={16} mx={0} fontSize="2xl" textAlign="center">
        Get started by editing <code>pages/index.tsx</code>
      </Text>
    </Flex>
  </Box>
);

export default Home;
